/**
 * POST /api/bins/register
 *
 * Dashboard endpoint — called when a logged-in user creates a new bin.
 * Requires an authenticated Supabase session (enforced by middleware + server client).
 *
 * This route creates the bin, assigns the user as owner, and initializes
 * all 3 sector rows (organic, inorganic, metal) with 0% fill level.
 *
 * The generated api_key is returned to the user so they can flash it
 * onto the ESP32 firmware (in the WIFI_CONFIG section of EcoBin.ino).
 *
 * Request body: { bin_name: string }
 * Response: { status: 'ok', bin: { id, bin_name, api_key } }
 */

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { serviceClient } from "@/lib/supabase/service";

type SectorType = "organic" | "inorganic" | "metal";

interface RegisterBinResponse {
  status: "ok" | "error";
  bin?: {
    id: string;
    bin_name: string;
    api_key: string;
  };
  message?: string;
}

export async function POST(request: Request): Promise<NextResponse<RegisterBinResponse>> {
  try {
    // ── Step 1: Verify user is authenticated ──
    // Uses the server client which reads the session from cookies
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        {
          status: "error",
          message: "Authentication required. Please log in.",
        },
        { status: 401 }
      );
    }

    // ── Step 2: Parse and validate request body ──
    let body: { bin_name?: string };
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { status: "error", message: "Invalid JSON body" },
        { status: 400 }
      );
    }

    const binName =
      body.bin_name && body.bin_name.trim() !== ""
        ? body.bin_name.trim()
        : "My EcoBin";

    // ── Step 3: Create the bin ──
    // The api_key is auto-generated by the database default:
    //   DEFAULT encode(gen_random_bytes(32), 'hex')
    const { data: newBin, error: binError } = await serviceClient
      .from("bins")
      .insert({ bin_name: binName })
      .select("id, bin_name, api_key")
      .single();

    if (binError || !newBin) {
      console.error("[bins/register] Bin creation error:", binError);
      return NextResponse.json(
        { status: "error", message: "Failed to create bin" },
        { status: 500 }
      );
    }

    // ── Step 4: Add user as owner ──
    const { error: memberError } = await serviceClient
      .from("bin_members")
      .insert({
        bin_id: newBin.id,
        user_id: user.id,
        rfid_uid: "",
        role: "owner",
      });

    if (memberError) {
      console.error("[bins/register] Member insert error:", memberError);
      // Rollback: delete the bin we just created
      await serviceClient.from("bins").delete().eq("id", newBin.id);
      return NextResponse.json(
        { status: "error", message: "Failed to assign bin ownership" },
        { status: 500 }
      );
    }

    // ── Step 5: Create 3 sector rows ──
    const sectorTypes: SectorType[] = ["organic", "inorganic", "metal"];
    const sectorRows = sectorTypes.map((st) => ({
      bin_id: newBin.id,
      sector_type: st,
      fill_level_percent: 0,
      weight_grams: 0,
      is_full: false,
    }));

    const { error: sectorError } = await serviceClient
      .from("sectors")
      .insert(sectorRows);

    if (sectorError) {
      console.error("[bins/register] Sector creation error:", sectorError);
      // Sectors failed but bin + member exist — log but don't fail
      // The sensor-data endpoint will create missing sectors on-the-fly
    }

    // ── Step 6: Return the new bin with its API key ──
    return NextResponse.json({
      status: "ok",
      bin: {
        id: newBin.id,
        bin_name: newBin.bin_name,
        api_key: newBin.api_key,
      },
    });
  } catch (error) {
    console.error("[bins/register] Unexpected error:", error);
    return NextResponse.json(
      { status: "error", message: "Internal server error" },
      { status: 500 }
    );
  }
}
